<x-guest-layout>
<section id="home" class="relative flex min-h-screen items-center overflow-hidden pb-20 pt-28">
    <div class="hero-grid absolute inset-0 opacity-40" aria-hidden="true"></div><div class="absolute -left-40 top-16 h-96 w-96 rounded-full bg-blue-600/20 blur-[120px]" aria-hidden="true"></div><div class="absolute -right-40 bottom-10 h-96 w-96 rounded-full bg-cyan-400/10 blur-[120px]" aria-hidden="true"></div>
    <div class="relative mx-auto grid w-full max-w-7xl items-center gap-16 px-5 sm:px-8 lg:grid-cols-[1.15fr_.85fr]">
        <div data-reveal>
            <div class="mb-7 inline-flex items-center gap-3 rounded-full border border-emerald-300/20 bg-emerald-300/5 px-4 py-2 text-xs font-semibold uppercase tracking-[.16em] text-emerald-300"><span class="relative flex h-2 w-2"><span class="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-300 opacity-60"></span><span class="relative h-2 w-2 rounded-full bg-emerald-300"></span></span>Available for opportunities</div>
            <p class="mb-4 text-sm font-semibold uppercase tracking-[.22em] text-cyan-300">Full Stack Developer · Indonesia</p>
            <h1 class="max-w-4xl text-5xl font-bold leading-[.98] tracking-[-.055em] text-white sm:text-6xl lg:text-7xl xl:text-[5.5rem]">Mengubah ide menjadi <span class="text-gradient">produk digital</span> yang bekerja.</h1>
            <p class="mt-7 max-w-2xl text-lg leading-8 text-slate-400">Saya Muhamad Fadhillah Dinurahman. Saya merancang dan membangun aplikasi web, mobile, serta sistem IoT yang cepat, terukur, dan mudah digunakan.</p>
            <div class="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#projects" class="btn-primary">Lihat karya pilihan <i class="bi bi-arrow-down-right" aria-hidden="true"></i></a><a href="mailto:m.fadhillah1218@gmail.com" class="btn-secondary">Hubungi saya <i class="bi bi-envelope" aria-hidden="true"></i></a></div>
            <div class="mt-10 flex flex-wrap items-center gap-x-8 gap-y-4 border-t border-white/10 pt-7 text-sm text-slate-400"><span><strong class="block text-xl text-white">Web</strong> Laravel · Vue</span><span><strong class="block text-xl text-white">Mobile</strong> Flutter</span><span><strong class="block text-xl text-white">IoT</strong> ESP32 · Realtime</span></div>
        </div>
        <div class="relative mx-auto w-full max-w-md" data-reveal><div class="absolute -inset-5 rotate-3 rounded-[2rem] border border-cyan-300/20 bg-cyan-300/5"></div><div class="relative overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-b from-slate-800 to-slate-950 px-8 pt-10 shadow-2xl shadow-blue-950/60"><div class="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan-300 to-transparent"></div><img src="/images/profile.png" alt="Muhamad Fadhillah Dinurahman" width="441" height="568" fetchpriority="high" class="relative mx-auto w-full max-w-[340px] select-none object-contain drop-shadow-2xl"><div class="absolute bottom-5 left-5 right-5 rounded-2xl border border-white/10 bg-slate-950/80 p-4 backdrop-blur-xl"><p class="text-xs uppercase tracking-[.18em] text-slate-500">Saat ini fokus pada</p><p id="typing-text" data-text='["Laravel applications","Flutter experiences","Connected IoT systems"]' class="mt-1 min-h-6 font-semibold text-white">Laravel applications</p></div></div></div>
    </div>
</section>
@include('public.projects') @include('public.about') @include('public.services') @include('public.skills') @include('public.contact')
</x-guest-layout>
