<nav x-data="portfolioNav()" x-init="init()" class="fixed inset-x-0 top-0 z-50 border-b transition duration-300" :class="scrolled ? 'border-white/10 bg-[#070b14]/90 shadow-2xl shadow-black/20 backdrop-blur-xl' : 'border-transparent bg-transparent'" aria-label="Navigasi utama">
    <div class="mx-auto flex h-20 max-w-7xl items-center px-5 sm:px-8">
        <a href="/#home" class="group flex min-h-11 items-center gap-3 rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300" aria-label="Fadhillah, kembali ke beranda">
            <span class="grid h-10 w-10 place-items-center rounded-xl border border-cyan-300/20 bg-cyan-300/10 font-bold text-cyan-300 transition group-hover:bg-cyan-300 group-hover:text-slate-950">FD</span>
            <span class="hidden text-sm font-semibold tracking-wide text-white sm:block">Fadhillah<span class="text-cyan-300">.</span></span>
        </a>
        <div class="absolute left-1/2 hidden -translate-x-1/2 items-center gap-1 md:flex">
            <template x-for="item in items" :key="item.id"><a :href="'/#' + item.id" class="relative rounded-lg px-4 py-3 text-sm font-medium transition focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300" :class="active === item.id ? 'text-white' : 'text-slate-400 hover:text-white'"><span x-text="item.label"></span><span class="absolute inset-x-4 bottom-1 h-px bg-cyan-300 transition" :class="active === item.id ? 'scale-x-100 opacity-100' : 'scale-x-0 opacity-0'"></span></a></template>
        </div>
        <a href="mailto:m.fadhillah1218@gmail.com" class="ml-auto hidden min-h-11 items-center gap-2 rounded-xl bg-cyan-300 px-5 text-sm font-bold text-slate-950 transition hover:bg-cyan-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-white md:inline-flex">Mari berdiskusi <i class="bi bi-arrow-up-right" aria-hidden="true"></i></a>
        <button @click="open = !open" type="button" class="ml-auto grid h-11 w-11 place-items-center rounded-xl border border-white/10 bg-white/5 text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300 md:hidden" :aria-expanded="open" aria-controls="mobile-menu" aria-label="Buka menu navigasi"><i class="bi text-xl" :class="open ? 'bi-x-lg' : 'bi-list'" aria-hidden="true"></i></button>
    </div>
    <div id="mobile-menu" x-cloak x-show="open" x-transition.opacity @click.outside="open = false" class="border-t border-white/10 bg-[#070b14]/95 px-5 py-5 backdrop-blur-xl md:hidden"><div class="mx-auto grid max-w-7xl gap-1"><template x-for="item in items" :key="item.id"><a :href="'/#' + item.id" @click="open = false" class="flex min-h-12 items-center rounded-xl px-4 text-base font-medium" :class="active === item.id ? 'bg-cyan-300/10 text-cyan-300' : 'text-slate-300'" x-text="item.label"></a></template></div></div>
</nav>
